local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("sploit", "Synapse")
local Tab = Window:NewTab("bedwars")
local Section = Tab:NewSection("bedwars 2.0")
Section:NewButton("vape", "vape by 7grandad", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()
    print("Clicked")
end)
local Section = Tab:NewSection("autofarm")
Section:NewButton("autofarm", "AISploit by GODCLUTCHER", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AlSploit/AlSploit/main/Loadstring"))()
    print("Clicked")
end)
local Tab = Window:NewTab("sploit")
local Section = Tab:NewSection("custom bedwars")
Section:NewButton("esp", "esp", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Lucasfin000/SpaceHub/main/UESP'))()
    print("Clicked")
end)
Section:NewButton("inf jump", "inf", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/BsGlitch/-nfJumps/main/BsGlitch"))();
    print("Clicked")
end)
